In [251]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Produção agrícola Brasil x RS 2022

In [252]:
dfbrasil = pd.read_csv('ranking-agricultura-valor-da-produo-brasil.csv')

In [253]:
dfbrasil

              produto        valor    unidade
0                Soja  345.422.469  Mil Reais
1       Milho em grão  137.743.946  Mil Reais
2      Cana-de-açúcar   93.478.262  Mil Reais
3                Café   51.813.884  Mil Reais
4    Algodão herbáceo   33.134.873  Mil Reais
..                ...          ...        ...
58       Chá-da-Índia        1.851  Mil Reais
59            Marmelo        1.795  Mil Reais
60               Juta           78  Mil Reais
61  Fonte: IBGE - PAM          NaN        NaN
62                NaN          NaN        NaN

[63 rows x 3 columns]

In [254]:
dfrs = pd.read_csv('ranking-agricultura-valor-da-produo-rio-grande-do-sul.csv')

In [255]:
dfrs

                produto       valor    unidade
0                  Soja  29.178.088  Mil Reais
1                 Arroz  10.989.888  Mil Reais
2                 Trigo   7.658.810  Mil Reais
3         Milho em grão   4.607.237  Mil Reais
4                  Fumo   4.028.551  Mil Reais
5                   Uva   1.227.459  Mil Reais
6              Mandioca   1.095.215  Mil Reais
7          Aveia branca     950.661  Mil Reais
8                  Maçã     716.313  Mil Reais
9                Batata     641.107  Mil Reais
10              Laranja     369.360  Mil Reais
11               Banana     331.577  Mil Reais
12            Tangerina     306.250  Mil Reais
13               Tomate     289.686  Mil Reais
14  Erva-mate (cultivo)     263.988  Mil Reais
15              Pêssego     245.685  Mil Reais
16               Feijão     244.938  Mil Reais
17               Cevada     244.938  Mil Reais
18               Cebola     207.081  Mil Reais
19             Melancia     165.136  Mil Reais
20                 Alho     137.079  Mil Reais
21       Cana-de-açúcar      97.996  Mil Reais
22                Caqui      87.310  Mil Reais
23                  Noz      63.534  Mil Reais
24                Limão      33.996  Mil Reais
25                Melão      25.833  Mil Reais
26                 Figo      25.046  Mil Reais
27            Triticale      22.374  Mil Reais
28                 Pera      19.689  Mil Reais
29      Linho (semente)      13.850  Mil Reais
30             Azeitona      12.305  Mil Reais
31             Amendoim      11.316  Mil Reais
32             Maracujá      11.074  Mil Reais
33               Goiaba      10.913  Mil Reais
34              Abacaxi      10.784  Mil Reais
35              Abacate      10.343  Mil Reais
36   Girassol (em grão)       7.240  Mil Reais
37                Sorgo       3.908  Mil Reais
38              Centeio       3.166  Mil Reais
39                Mamão       1.947  Mil Reais
40                Manga       1.829  Mil Reais
41      Ervilha em grão         496  Mil Reais
42              Marmelo         156  Mil Reais
43                 Fava          75  Mil Reais
44    Fonte: IBGE - PAM         NaN        NaN
45                  NaN         NaN        NaN

In [256]:
dfbrasil = dfbrasil.dropna()

In [257]:
dfbrasil

             produto        valor    unidade
0               Soja  345.422.469  Mil Reais
1      Milho em grão  137.743.946  Mil Reais
2     Cana-de-açúcar   93.478.262  Mil Reais
3               Café   51.813.884  Mil Reais
4   Algodão herbáceo   33.134.873  Mil Reais
..               ...          ...        ...
56   Linho (semente)       13.850  Mil Reais
57             Malva        8.730  Mil Reais
58      Chá-da-Índia        1.851  Mil Reais
59           Marmelo        1.795  Mil Reais
60              Juta           78  Mil Reais

[61 rows x 3 columns]

In [258]:
dfrs = dfrs.dropna()

In [259]:
dfrs

                produto       valor    unidade
0                  Soja  29.178.088  Mil Reais
1                 Arroz  10.989.888  Mil Reais
2                 Trigo   7.658.810  Mil Reais
3         Milho em grão   4.607.237  Mil Reais
4                  Fumo   4.028.551  Mil Reais
5                   Uva   1.227.459  Mil Reais
6              Mandioca   1.095.215  Mil Reais
7          Aveia branca     950.661  Mil Reais
8                  Maçã     716.313  Mil Reais
9                Batata     641.107  Mil Reais
10              Laranja     369.360  Mil Reais
11               Banana     331.577  Mil Reais
12            Tangerina     306.250  Mil Reais
13               Tomate     289.686  Mil Reais
14  Erva-mate (cultivo)     263.988  Mil Reais
15              Pêssego     245.685  Mil Reais
16               Feijão     244.938  Mil Reais
17               Cevada     244.938  Mil Reais
18               Cebola     207.081  Mil Reais
19             Melancia     165.136  Mil Reais
20                 Alho     137.079  Mil Reais
21       Cana-de-açúcar      97.996  Mil Reais
22                Caqui      87.310  Mil Reais
23                  Noz      63.534  Mil Reais
24                Limão      33.996  Mil Reais
25                Melão      25.833  Mil Reais
26                 Figo      25.046  Mil Reais
27            Triticale      22.374  Mil Reais
28                 Pera      19.689  Mil Reais
29      Linho (semente)      13.850  Mil Reais
30             Azeitona      12.305  Mil Reais
31             Amendoim      11.316  Mil Reais
32             Maracujá      11.074  Mil Reais
33               Goiaba      10.913  Mil Reais
34              Abacaxi      10.784  Mil Reais
35              Abacate      10.343  Mil Reais
36   Girassol (em grão)       7.240  Mil Reais
37                Sorgo       3.908  Mil Reais
38              Centeio       3.166  Mil Reais
39                Mamão       1.947  Mil Reais
40                Manga       1.829  Mil Reais
41      Ervilha em grão         496  Mil Reais
42              Marmelo         156  Mil Reais
43                 Fava          75  Mil Reais

In [260]:
dfrs = dfrs.rename(columns ={'Produto RS': 'Produto', 'valor': 'Valor produzido RS'})

In [261]:
dfrs

                produto Valor produzido RS    unidade
0                  Soja         29.178.088  Mil Reais
1                 Arroz         10.989.888  Mil Reais
2                 Trigo          7.658.810  Mil Reais
3         Milho em grão          4.607.237  Mil Reais
4                  Fumo          4.028.551  Mil Reais
5                   Uva          1.227.459  Mil Reais
6              Mandioca          1.095.215  Mil Reais
7          Aveia branca            950.661  Mil Reais
8                  Maçã            716.313  Mil Reais
9                Batata            641.107  Mil Reais
10              Laranja            369.360  Mil Reais
11               Banana            331.577  Mil Reais
12            Tangerina            306.250  Mil Reais
13               Tomate            289.686  Mil Reais
14  Erva-mate (cultivo)            263.988  Mil Reais
15              Pêssego            245.685  Mil Reais
16               Feijão            244.938  Mil Reais
17               Cevada            244.938  Mil Reais
18               Cebola            207.081  Mil Reais
19             Melancia            165.136  Mil Reais
20                 Alho            137.079  Mil Reais
21       Cana-de-açúcar             97.996  Mil Reais
22                Caqui             87.310  Mil Reais
23                  Noz             63.534  Mil Reais
24                Limão             33.996  Mil Reais
25                Melão             25.833  Mil Reais
26                 Figo             25.046  Mil Reais
27            Triticale             22.374  Mil Reais
28                 Pera             19.689  Mil Reais
29      Linho (semente)             13.850  Mil Reais
30             Azeitona             12.305  Mil Reais
31             Amendoim             11.316  Mil Reais
32             Maracujá             11.074  Mil Reais
33               Goiaba             10.913  Mil Reais
34              Abacaxi             10.784  Mil Reais
35              Abacate             10.343  Mil Reais
36   Girassol (em grão)              7.240  Mil Reais
37                Sorgo              3.908  Mil Reais
38              Centeio              3.166  Mil Reais
39                Mamão              1.947  Mil Reais
40                Manga              1.829  Mil Reais
41      Ervilha em grão                496  Mil Reais
42              Marmelo                156  Mil Reais
43                 Fava                 75  Mil Reais

In [262]:
dfbrasil = dfbrasil.rename(columns ={'Produto Brasil': 'Produto', 'Valor produzido': 'Valor produzido BR'})

In [263]:
dfbrasil

             produto        valor    unidade
0               Soja  345.422.469  Mil Reais
1      Milho em grão  137.743.946  Mil Reais
2     Cana-de-açúcar   93.478.262  Mil Reais
3               Café   51.813.884  Mil Reais
4   Algodão herbáceo   33.134.873  Mil Reais
..               ...          ...        ...
56   Linho (semente)       13.850  Mil Reais
57             Malva        8.730  Mil Reais
58      Chá-da-Índia        1.851  Mil Reais
59           Marmelo        1.795  Mil Reais
60              Juta           78  Mil Reais

[61 rows x 3 columns]

In [264]:
dfbrasil = dfbrasil.drop(columns={'unidade'})

In [265]:
dfbrasil

             produto        valor
0               Soja  345.422.469
1      Milho em grão  137.743.946
2     Cana-de-açúcar   93.478.262
3               Café   51.813.884
4   Algodão herbáceo   33.134.873
..               ...          ...
56   Linho (semente)       13.850
57             Malva        8.730
58      Chá-da-Índia        1.851
59           Marmelo        1.795
60              Juta           78

[61 rows x 2 columns]

In [266]:
dfbrasil['valor'] = dfbrasil['valor'].str.replace(r'[^\d\.\-]', '', regex=True).str.strip()

In [267]:
dfbrasil['valor']

0     345.422.469
1     137.743.946
2      93.478.262
3      51.813.884
4      33.134.873
         ...
56         13.850
57          8.730
58          1.851
59          1.795
60             78
Name: valor, Length: 61, dtype: object

In [268]:
dfbrasil['valor'][0]

'345.422.469'

In [269]:
dfbrasil['valor'][0].replace('.','')

'345422469'

In [270]:
dfbrasil = pd.DataFrame(dfbrasil)

In [271]:
print(dfbrasil.dtypes)

produto    object
valor      object
dtype: object

In [272]:
dfbrasil

             produto        valor
0               Soja  345.422.469
1      Milho em grão  137.743.946
2     Cana-de-açúcar   93.478.262
3               Café   51.813.884
4   Algodão herbáceo   33.134.873
..               ...          ...
56   Linho (semente)       13.850
57             Malva        8.730
58      Chá-da-Índia        1.851
59           Marmelo        1.795
60              Juta           78

[61 rows x 2 columns]

In [273]:
dfcombinado = pd.merge(dfbrasil, dfrs, how='inner')

In [274]:
dfcombinado

                produto        valor Valor produzido RS    unidade
0                  Soja  345.422.469         29.178.088  Mil Reais
1         Milho em grão  137.743.946          4.607.237  Mil Reais
2        Cana-de-açúcar   93.478.262             97.996  Mil Reais
3                 Trigo   15.696.828          7.658.810  Mil Reais
4                 Arroz   15.530.452         10.989.888  Mil Reais
5              Mandioca   15.298.408          1.095.215  Mil Reais
6               Laranja   14.367.012            369.360  Mil Reais
7                Banana   11.918.249            331.577  Mil Reais
8                Tomate    8.656.263            289.686  Mil Reais
9                  Fumo    8.541.349          4.028.551  Mil Reais
10               Batata    6.728.524            641.107  Mil Reais
11                  Uva    4.536.903          1.227.459  Mil Reais
12               Cebola    4.107.583            207.081  Mil Reais
13                Sorgo    2.910.545              3.908  Mil Reais
14              Abacaxi    2.758.106             10.784  Mil Reais
15             Amendoim    2.584.944             11.316  Mil Reais
16                Mamão    2.402.452              1.947  Mil Reais
17                Limão    2.076.875             33.996  Mil Reais
18                Manga    2.074.489              1.829  Mil Reais
19                 Maçã    1.975.266            716.313  Mil Reais
20             Maracujá    1.972.578             11.074  Mil Reais
21                 Alho    1.897.787            137.079  Mil Reais
22             Melancia    1.882.802            165.136  Mil Reais
23            Tangerina    1.597.950            306.250  Mil Reais
24         Aveia branca    1.479.083            950.661  Mil Reais
25               Goiaba    1.109.140             10.913  Mil Reais
26               Feijão      916.254            244.938  Mil Reais
27               Cevada      916.254            244.938  Mil Reais
28                Melão      877.273             25.833  Mil Reais
29              Abacate      857.128             10.343  Mil Reais
30  Erva-mate (cultivo)      846.541            263.988  Mil Reais
31              Pêssego      480.802            245.685  Mil Reais
32                Caqui      428.730             87.310  Mil Reais
33            Triticale      165.207             22.374  Mil Reais
34   Girassol (em grão)      152.098              7.240  Mil Reais
35                 Figo      136.224             25.046  Mil Reais
36                 Fava       90.396                 75  Mil Reais
37                  Noz       71.728             63.534  Mil Reais
38                 Pera       48.018             19.689  Mil Reais
39             Azeitona       20.355             12.305  Mil Reais
40              Centeio       17.630              3.166  Mil Reais
41      Ervilha em grão       17.222                496  Mil Reais
42      Linho (semente)       13.850             13.850  Mil Reais
43              Marmelo        1.795                156  Mil Reais

In [275]:
dfcombinado = dfcombinado.rename(columns ={'valor': 'Valor Produzido BR'})

In [276]:
dfcombinado

                produto Valor Produzido BR Valor produzido RS    unidade
0                  Soja        345.422.469         29.178.088  Mil Reais
1         Milho em grão        137.743.946          4.607.237  Mil Reais
2        Cana-de-açúcar         93.478.262             97.996  Mil Reais
3                 Trigo         15.696.828          7.658.810  Mil Reais
4                 Arroz         15.530.452         10.989.888  Mil Reais
5              Mandioca         15.298.408          1.095.215  Mil Reais
6               Laranja         14.367.012            369.360  Mil Reais
7                Banana         11.918.249            331.577  Mil Reais
8                Tomate          8.656.263            289.686  Mil Reais
9                  Fumo          8.541.349          4.028.551  Mil Reais
10               Batata          6.728.524            641.107  Mil Reais
11                  Uva          4.536.903          1.227.459  Mil Reais
12               Cebola          4.107.583            207.081  Mil Reais
13                Sorgo          2.910.545              3.908  Mil Reais
14              Abacaxi          2.758.106             10.784  Mil Reais
15             Amendoim          2.584.944             11.316  Mil Reais
16                Mamão          2.402.452              1.947  Mil Reais
17                Limão          2.076.875             33.996  Mil Reais
18                Manga          2.074.489              1.829  Mil Reais
19                 Maçã          1.975.266            716.313  Mil Reais
20             Maracujá          1.972.578             11.074  Mil Reais
21                 Alho          1.897.787            137.079  Mil Reais
22             Melancia          1.882.802            165.136  Mil Reais
23            Tangerina          1.597.950            306.250  Mil Reais
24         Aveia branca          1.479.083            950.661  Mil Reais
25               Goiaba          1.109.140             10.913  Mil Reais
26               Feijão            916.254            244.938  Mil Reais
27               Cevada            916.254            244.938  Mil Reais
28                Melão            877.273             25.833  Mil Reais
29              Abacate            857.128             10.343  Mil Reais
30  Erva-mate (cultivo)            846.541            263.988  Mil Reais
31              Pêssego            480.802            245.685  Mil Reais
32                Caqui            428.730             87.310  Mil Reais
33            Triticale            165.207             22.374  Mil Reais
34   Girassol (em grão)            152.098              7.240  Mil Reais
35                 Figo            136.224             25.046  Mil Reais
36                 Fava             90.396                 75  Mil Reais
37                  Noz             71.728             63.534  Mil Reais
38                 Pera             48.018             19.689  Mil Reais
39             Azeitona             20.355             12.305  Mil Reais
40              Centeio             17.630              3.166  Mil Reais
41      Ervilha em grão             17.222                496  Mil Reais
42      Linho (semente)             13.850             13.850  Mil Reais
43              Marmelo              1.795                156  Mil Reais

In [277]:
dfcombinado = dfcombinado.drop(columns={'unidade'})

In [278]:
dfcombinado

                produto Valor Produzido BR Valor produzido RS
0                  Soja        345.422.469         29.178.088
1         Milho em grão        137.743.946          4.607.237
2        Cana-de-açúcar         93.478.262             97.996
3                 Trigo         15.696.828          7.658.810
4                 Arroz         15.530.452         10.989.888
5              Mandioca         15.298.408          1.095.215
6               Laranja         14.367.012            369.360
7                Banana         11.918.249            331.577
8                Tomate          8.656.263            289.686
9                  Fumo          8.541.349          4.028.551
10               Batata          6.728.524            641.107
11                  Uva          4.536.903          1.227.459
12               Cebola          4.107.583            207.081
13                Sorgo          2.910.545              3.908
14              Abacaxi          2.758.106             10.784
15             Amendoim          2.584.944             11.316
16                Mamão          2.402.452              1.947
17                Limão          2.076.875             33.996
18                Manga          2.074.489              1.829
19                 Maçã          1.975.266            716.313
20             Maracujá          1.972.578             11.074
21                 Alho          1.897.787            137.079
22             Melancia          1.882.802            165.136
23            Tangerina          1.597.950            306.250
24         Aveia branca          1.479.083            950.661
25               Goiaba          1.109.140             10.913
26               Feijão            916.254            244.938
27               Cevada            916.254            244.938
28                Melão            877.273             25.833
29              Abacate            857.128             10.343
30  Erva-mate (cultivo)            846.541            263.988
31              Pêssego            480.802            245.685
32                Caqui            428.730             87.310
33            Triticale            165.207             22.374
34   Girassol (em grão)            152.098              7.240
35                 Figo            136.224             25.046
36                 Fava             90.396                 75
37                  Noz             71.728             63.534
38                 Pera             48.018             19.689
39             Azeitona             20.355             12.305
40              Centeio             17.630              3.166
41      Ervilha em grão             17.222                496
42      Linho (semente)             13.850             13.850
43              Marmelo              1.795                156

In [279]:
dfcombinado['Valor Produzido BR'] = dfcombinado['Valor Produzido BR'].str.replace('.', '').astype(str)
dfcombinado['Valor produzido RS'] = dfcombinado['Valor produzido RS'].str.replace('.', '').astype(str)

In [280]:
dfcombinado

                produto Valor Produzido BR Valor produzido RS
0                  Soja          345422469           29178088
1         Milho em grão          137743946            4607237
2        Cana-de-açúcar           93478262              97996
3                 Trigo           15696828            7658810
4                 Arroz           15530452           10989888
5              Mandioca           15298408            1095215
6               Laranja           14367012             369360
7                Banana           11918249             331577
8                Tomate            8656263             289686
9                  Fumo            8541349            4028551
10               Batata            6728524             641107
11                  Uva            4536903            1227459
12               Cebola            4107583             207081
13                Sorgo            2910545               3908
14              Abacaxi            2758106              10784
15             Amendoim            2584944              11316
16                Mamão            2402452               1947
17                Limão            2076875              33996
18                Manga            2074489               1829
19                 Maçã            1975266             716313
20             Maracujá            1972578              11074
21                 Alho            1897787             137079
22             Melancia            1882802             165136
23            Tangerina            1597950             306250
24         Aveia branca            1479083             950661
25               Goiaba            1109140              10913
26               Feijão             916254             244938
27               Cevada             916254             244938
28                Melão             877273              25833
29              Abacate             857128              10343
30  Erva-mate (cultivo)             846541             263988
31              Pêssego             480802             245685
32                Caqui             428730              87310
33            Triticale             165207              22374
34   Girassol (em grão)             152098               7240
35                 Figo             136224              25046
36                 Fava              90396                 75
37                  Noz              71728              63534
38                 Pera              48018              19689
39             Azeitona              20355              12305
40              Centeio              17630               3166
41      Ervilha em grão              17222                496
42      Linho (semente)              13850              13850
43              Marmelo               1795                156

In [281]:
dfcombinado['Valor Produzido BR'] = dfcombinado['Valor Produzido BR'].astype(int)
dfcombinado['Valor produzido RS'] = dfcombinado['Valor produzido RS'].astype(int)

In [282]:
dfcombinado

                produto  Valor Produzido BR  Valor produzido RS
0                  Soja           345422469            29178088
1         Milho em grão           137743946             4607237
2        Cana-de-açúcar            93478262               97996
3                 Trigo            15696828             7658810
4                 Arroz            15530452            10989888
5              Mandioca            15298408             1095215
6               Laranja            14367012              369360
7                Banana            11918249              331577
8                Tomate             8656263              289686
9                  Fumo             8541349             4028551
10               Batata             6728524              641107
11                  Uva             4536903             1227459
12               Cebola             4107583              207081
13                Sorgo             2910545                3908
14              Abacaxi             2758106               10784
15             Amendoim             2584944               11316
16                Mamão             2402452                1947
17                Limão             2076875               33996
18                Manga             2074489                1829
19                 Maçã             1975266              716313
20             Maracujá             1972578               11074
21                 Alho             1897787              137079
22             Melancia             1882802              165136
23            Tangerina             1597950              306250
24         Aveia branca             1479083              950661
25               Goiaba             1109140               10913
26               Feijão              916254              244938
27               Cevada              916254              244938
28                Melão              877273               25833
29              Abacate              857128               10343
30  Erva-mate (cultivo)              846541              263988
31              Pêssego              480802              245685
32                Caqui              428730               87310
33            Triticale              165207               22374
34   Girassol (em grão)              152098                7240
35                 Figo              136224               25046
36                 Fava               90396                  75
37                  Noz               71728               63534
38                 Pera               48018               19689
39             Azeitona               20355               12305
40              Centeio               17630                3166
41      Ervilha em grão               17222                 496
42      Linho (semente)               13850               13850
43              Marmelo                1795                 156

In [284]:
dfcombinado['Diferença'] = dfcombinado['Valor Produzido BR'] - dfcombinado['Valor produzido RS']

In [285]:
dfcombinado

                produto  Valor Produzido BR  Valor produzido RS  Diferença
0                  Soja           345422469            29178088  316244381
1         Milho em grão           137743946             4607237  133136709
2        Cana-de-açúcar            93478262               97996   93380266
3                 Trigo            15696828             7658810    8038018
4                 Arroz            15530452            10989888    4540564
5              Mandioca            15298408             1095215   14203193
6               Laranja            14367012              369360   13997652
7                Banana            11918249              331577   11586672
8                Tomate             8656263              289686    8366577
9                  Fumo             8541349             4028551    4512798
10               Batata             6728524              641107    6087417
11                  Uva             4536903             1227459    3309444
12               Cebola             4107583              207081    3900502
13                Sorgo             2910545                3908    2906637
14              Abacaxi             2758106               10784    2747322
15             Amendoim             2584944               11316    2573628
16                Mamão             2402452                1947    2400505
17                Limão             2076875               33996    2042879
18                Manga             2074489                1829    2072660
19                 Maçã             1975266              716313    1258953
20             Maracujá             1972578               11074    1961504
21                 Alho             1897787              137079    1760708
22             Melancia             1882802              165136    1717666
23            Tangerina             1597950              306250    1291700
24         Aveia branca             1479083              950661     528422
25               Goiaba             1109140               10913    1098227
26               Feijão              916254              244938     671316
27               Cevada              916254              244938     671316
28                Melão              877273               25833     851440
29              Abacate              857128               10343     846785
30  Erva-mate (cultivo)              846541              263988     582553
31              Pêssego              480802              245685     235117
32                Caqui              428730               87310     341420
33            Triticale              165207               22374     142833
34   Girassol (em grão)              152098                7240     144858
35                 Figo              136224               25046     111178
36                 Fava               90396                  75      90321
37                  Noz               71728               63534       8194
38                 Pera               48018               19689      28329
39             Azeitona               20355               12305       8050
40              Centeio               17630                3166      14464
41      Ervilha em grão               17222                 496      16726
42      Linho (semente)               13850               13850          0
43              Marmelo                1795                 156       1639

In [299]:
dfcombinado['Quantidade RS (%)'] = (dfcombinado['Valor produzido RS'] / dfcombinado['Valor Produzido BR']) * 100

In [300]:
dfcombinado

,produto,Valor Produzido BR,Valor produzido RS,Diferença,Quantidade RS,Quantidade RS (%)
0,Soja,345422469,29178088,316244381,8.447073,8.447073
1,Milho em grão,137743946,4607237,133136709,3.344784,3.344784
2,Cana-de-açúcar,93478262,97996,93380266,0.104833,0.104833
3,Trigo,15696828,7658810,8038018,48.792087,48.792087
4,Arroz,15530452,10989888,4540564,70.763478,70.763478
5,Mandioca,15298408,1095215,14203193,7.159013,7.159013
6,Laranja,14367012,369360,13997652,2.570889,2.570889
7,Banana,11918249,331577,11586672,2.782095,2.782095
8,Tomate,8656263,289686,8366577,3.346548,3.346548
9,Fumo,8541349,4028551,4512798,47.165278,47.165278
10,Batata,6728524,641107,6087417,9.528197,9.528197
11,Uva,4536903,1227459,3309444,27.054998,27.054998
12,Cebola,4107583,207081,3900502,5.041432,5.041432
13,Sorgo,2910545,3908,2906637,0.134270,0.134270
14,Abacaxi,2758106,10784,2747322,0.390993,0.390993
15,Amendoim,2584944,11316,2573628,0.437766,0.437766
16,Mamão,2402452,1947,2400505,0.081042,0.081042
17,Limão,2076875,33996,2042879,1.636882,1.636882
18,Manga,2074489,1829,2072660,0.088166,0.088166
19,Maçã,1975266,716313,1258953,36.264128,36.264128
20,Maracujá,1972578,11074,1961504,0.561397,0.561397
21,Alho,1897787,137079,1760708,7.223097,7.223097
22,Melancia,1882802,165136,1717666,8.770758,8.770758
23,Tangerina,1597950,306250,1291700,19.165180,19.165180
24,Aveia branca,1479083,950661,528422,64.273675,64.273675
25,Goiaba,1109140,10913,1098227,0.983915,0.983915
26,Feijão,916254,244938,671316,26.732544,26.732544
27,Cevada,916254,244938,671316,26.732544,26.732544
28,Melão,877273,25833,851440,2.944693,2.944693
29,Abacate,857128,10343,846785,1.206704,1.206704
30,Erva-mate (cultivo),846541,263988,582553,31.184314,31.184314
31,Pêssego,480802,245685,235117,51.098997,51.098997
32,Caqui,428730,87310,341420,20.364798,20.364798
33,Triticale,165207,22374,142833,13.543010,13.543010
34,Girassol (em grão),152098,7240,144858,4.760089,4.760089
35,Figo,136224,25046,111178,18.385894,18.385894
36,Fava,90396,75,90321,0.082968,0.082968
37,Noz,71728,63534,8194,88.576288,88.576288
38,Pera,48018,19689,28329,41.003374,41.003374
39,Azeitona,20355,12305,8050,60.451977,60.451977
40,Centeio,17630,3166,14464,17.958026,17.958026
41,Ervilha em grão,17222,496,16726,2.880037,2.880037
42,Linho (semente),13850,13850,0,100.000000,100.000000
43,Marmelo,1795,156,1639,8.690808,8.690808

In [302]:
dfcombinado['Quantidade RS (%)'] = dfcombinado['Quantidade RS (%)'].round(2)
dfcombinado

,produto,Valor Produzido BR,Valor produzido RS,Diferença,Quantidade RS,Quantidade RS (%)
0,Soja,345422469,29178088,316244381,8.447073,8.45
1,Milho em grão,137743946,4607237,133136709,3.344784,3.34
2,Cana-de-açúcar,93478262,97996,93380266,0.104833,0.10
3,Trigo,15696828,7658810,8038018,48.792087,48.79
4,Arroz,15530452,10989888,4540564,70.763478,70.76
5,Mandioca,15298408,1095215,14203193,7.159013,7.16
6,Laranja,14367012,369360,13997652,2.570889,2.57
7,Banana,11918249,331577,11586672,2.782095,2.78
8,Tomate,8656263,289686,8366577,3.346548,3.35
9,Fumo,8541349,4028551,4512798,47.165278,47.17
10,Batata,6728524,641107,6087417,9.528197,9.53
11,Uva,4536903,1227459,3309444,27.054998,27.05
12,Cebola,4107583,207081,3900502,5.041432,5.04
13,Sorgo,2910545,3908,2906637,0.134270,0.13
14,Abacaxi,2758106,10784,2747322,0.390993,0.39
15,Amendoim,2584944,11316,2573628,0.437766,0.44
16,Mamão,2402452,1947,2400505,0.081042,0.08
17,Limão,2076875,33996,2042879,1.636882,1.64
18,Manga,2074489,1829,2072660,0.088166,0.09
19,Maçã,1975266,716313,1258953,36.264128,36.26
20,Maracujá,1972578,11074,1961504,0.561397,0.56
21,Alho,1897787,137079,1760708,7.223097,7.22
22,Melancia,1882802,165136,1717666,8.770758,8.77
23,Tangerina,1597950,306250,1291700,19.165180,19.17
24,Aveia branca,1479083,950661,528422,64.273675,64.27
25,Goiaba,1109140,10913,1098227,0.983915,0.98
26,Feijão,916254,244938,671316,26.732544,26.73
27,Cevada,916254,244938,671316,26.732544,26.73
28,Melão,877273,25833,851440,2.944693,2.94
29,Abacate,857128,10343,846785,1.206704,1.21
30,Erva-mate (cultivo),846541,263988,582553,31.184314,31.18
31,Pêssego,480802,245685,235117,51.098997,51.10
32,Caqui,428730,87310,341420,20.364798,20.36
33,Triticale,165207,22374,142833,13.543010,13.54
34,Girassol (em grão),152098,7240,144858,4.760089,4.76
35,Figo,136224,25046,111178,18.385894,18.39
36,Fava,90396,75,90321,0.082968,0.08
37,Noz,71728,63534,8194,88.576288,88.58
38,Pera,48018,19689,28329,41.003374,41.00
39,Azeitona,20355,12305,8050,60.451977,60.45
40,Centeio,17630,3166,14464,17.958026,17.96
41,Ervilha em grão,17222,496,16726,2.880037,2.88
42,Linho (semente),13850,13850,0,100.000000,100.00
43,Marmelo,1795,156,1639,8.690808,8.69

In [303]:
dfcombinado['Quantidade RS (%)'] = pd.to_numeric(dfcombinado['Quantidade RS (%)'], errors='coerce')

In [304]:
dfcombinado

,produto,Valor Produzido BR,Valor produzido RS,Diferença,Quantidade RS,Quantidade RS (%)
0,Soja,345422469,29178088,316244381,8.447073,8.45
1,Milho em grão,137743946,4607237,133136709,3.344784,3.34
2,Cana-de-açúcar,93478262,97996,93380266,0.104833,0.10
3,Trigo,15696828,7658810,8038018,48.792087,48.79
4,Arroz,15530452,10989888,4540564,70.763478,70.76
5,Mandioca,15298408,1095215,14203193,7.159013,7.16
6,Laranja,14367012,369360,13997652,2.570889,2.57
7,Banana,11918249,331577,11586672,2.782095,2.78
8,Tomate,8656263,289686,8366577,3.346548,3.35
9,Fumo,8541349,4028551,4512798,47.165278,47.17
10,Batata,6728524,641107,6087417,9.528197,9.53
11,Uva,4536903,1227459,3309444,27.054998,27.05
12,Cebola,4107583,207081,3900502,5.041432,5.04
13,Sorgo,2910545,3908,2906637,0.134270,0.13
14,Abacaxi,2758106,10784,2747322,0.390993,0.39
15,Amendoim,2584944,11316,2573628,0.437766,0.44
16,Mamão,2402452,1947,2400505,0.081042,0.08
17,Limão,2076875,33996,2042879,1.636882,1.64
18,Manga,2074489,1829,2072660,0.088166,0.09
19,Maçã,1975266,716313,1258953,36.264128,36.26
20,Maracujá,1972578,11074,1961504,0.561397,0.56
21,Alho,1897787,137079,1760708,7.223097,7.22
22,Melancia,1882802,165136,1717666,8.770758,8.77
23,Tangerina,1597950,306250,1291700,19.165180,19.17
24,Aveia branca,1479083,950661,528422,64.273675,64.27
25,Goiaba,1109140,10913,1098227,0.983915,0.98
26,Feijão,916254,244938,671316,26.732544,26.73
27,Cevada,916254,244938,671316,26.732544,26.73
28,Melão,877273,25833,851440,2.944693,2.94
29,Abacate,857128,10343,846785,1.206704,1.21
30,Erva-mate (cultivo),846541,263988,582553,31.184314,31.18
31,Pêssego,480802,245685,235117,51.098997,51.10
32,Caqui,428730,87310,341420,20.364798,20.36
33,Triticale,165207,22374,142833,13.543010,13.54
34,Girassol (em grão),152098,7240,144858,4.760089,4.76
35,Figo,136224,25046,111178,18.385894,18.39
36,Fava,90396,75,90321,0.082968,0.08
37,Noz,71728,63534,8194,88.576288,88.58
38,Pera,48018,19689,28329,41.003374,41.00
39,Azeitona,20355,12305,8050,60.451977,60.45
40,Centeio,17630,3166,14464,17.958026,17.96
41,Ervilha em grão,17222,496,16726,2.880037,2.88
42,Linho (semente),13850,13850,0,100.000000,100.00
43,Marmelo,1795,156,1639,8.690808,8.69

In [305]:
df_classificado = dfcombinado.sort_values(by='Quantidade RS (%)', ascending=False)

In [306]:
df_classificado

,produto,Valor Produzido BR,Valor produzido RS,Diferença,Quantidade RS,Quantidade RS (%)
42,Linho (semente),13850,13850,0,100.000000,100.00
37,Noz,71728,63534,8194,88.576288,88.58
4,Arroz,15530452,10989888,4540564,70.763478,70.76
24,Aveia branca,1479083,950661,528422,64.273675,64.27
39,Azeitona,20355,12305,8050,60.451977,60.45
31,Pêssego,480802,245685,235117,51.098997,51.10
3,Trigo,15696828,7658810,8038018,48.792087,48.79
9,Fumo,8541349,4028551,4512798,47.165278,47.17
38,Pera,48018,19689,28329,41.003374,41.00
19,Maçã,1975266,716313,1258953,36.264128,36.26
30,Erva-mate (cultivo),846541,263988,582553,31.184314,31.18
11,Uva,4536903,1227459,3309444,27.054998,27.05
27,Cevada,916254,244938,671316,26.732544,26.73
26,Feijão,916254,244938,671316,26.732544,26.73
32,Caqui,428730,87310,341420,20.364798,20.36
23,Tangerina,1597950,306250,1291700,19.165180,19.17
35,Figo,136224,25046,111178,18.385894,18.39
40,Centeio,17630,3166,14464,17.958026,17.96
33,Triticale,165207,22374,142833,13.543010,13.54
10,Batata,6728524,641107,6087417,9.528197,9.53
22,Melancia,1882802,165136,1717666,8.770758,8.77
43,Marmelo,1795,156,1639,8.690808,8.69
0,Soja,345422469,29178088,316244381,8.447073,8.45
21,Alho,1897787,137079,1760708,7.223097,7.22
5,Mandioca,15298408,1095215,14203193,7.159013,7.16
12,Cebola,4107583,207081,3900502,5.041432,5.04
34,Girassol (em grão),152098,7240,144858,4.760089,4.76
8,Tomate,8656263,289686,8366577,3.346548,3.35
1,Milho em grão,137743946,4607237,133136709,3.344784,3.34
28,Melão,877273,25833,851440,2.944693,2.94
41,Ervilha em grão,17222,496,16726,2.880037,2.88
7,Banana,11918249,331577,11586672,2.782095,2.78
6,Laranja,14367012,369360,13997652,2.570889,2.57
17,Limão,2076875,33996,2042879,1.636882,1.64
29,Abacate,857128,10343,846785,1.206704,1.21
25,Goiaba,1109140,10913,1098227,0.983915,0.98
20,Maracujá,1972578,11074,1961504,0.561397,0.56
15,Amendoim,2584944,11316,2573628,0.437766,0.44
14,Abacaxi,2758106,10784,2747322,0.390993,0.39
13,Sorgo,2910545,3908,2906637,0.134270,0.13
2,Cana-de-açúcar,93478262,97996,93380266,0.104833,0.10
18,Manga,2074489,1829,2072660,0.088166,0.09
16,Mamão,2402452,1947,2400505,0.081042,0.08
36,Fava,90396,75,90321,0.082968,0.08

In [307]:
top_10 = df_classificado.head(10)

In [308]:
top_10

,produto,Valor Produzido BR,Valor produzido RS,Diferença,Quantidade RS,Quantidade RS (%)
42,Linho (semente),13850,13850,0,100.000000,100.00
37,Noz,71728,63534,8194,88.576288,88.58
4,Arroz,15530452,10989888,4540564,70.763478,70.76
24,Aveia branca,1479083,950661,528422,64.273675,64.27
39,Azeitona,20355,12305,8050,60.451977,60.45
31,Pêssego,480802,245685,235117,51.098997,51.10
3,Trigo,15696828,7658810,8038018,48.792087,48.79
9,Fumo,8541349,4028551,4512798,47.165278,47.17
38,Pera,48018,19689,28329,41.003374,41.00
19,Maçã,1975266,716313,1258953,36.264128,36.26

In [309]:
import plotly.express as px

In [315]:
fig = px.bar(top_10, x='produto', y='Quantidade RS (%)', title='Top 10 Maiores Quantidades Produzidas pelo RS em relação ao Brasil')
fig.update_traces(marker_color='rgb(200,130,100)', marker_line_color='rgb(8,48,107)', marker_line_width=1.5, opacity=0.6)
fig.update_layout(xaxis_tickangle=-45)
fig.show()

In [317]:
top_10_menores = df_classificado.tail(10)

In [318]:
top_10_menores

,produto,Valor Produzido BR,Valor produzido RS,Diferença,Quantidade RS,Quantidade RS (%)
29,Abacate,857128,10343,846785,1.206704,1.21
25,Goiaba,1109140,10913,1098227,0.983915,0.98
20,Maracujá,1972578,11074,1961504,0.561397,0.56
15,Amendoim,2584944,11316,2573628,0.437766,0.44
14,Abacaxi,2758106,10784,2747322,0.390993,0.39
13,Sorgo,2910545,3908,2906637,0.134270,0.13
2,Cana-de-açúcar,93478262,97996,93380266,0.104833,0.10
18,Manga,2074489,1829,2072660,0.088166,0.09
16,Mamão,2402452,1947,2400505,0.081042,0.08
36,Fava,90396,75,90321,0.082968,0.08

In [319]:
fig = px.bar(top_10_menores, x='produto', y='Quantidade RS (%)', title='Top 10 Maiores Quantidades Produzidas pelo RS em relação ao Brasil')
fig.update_traces(marker_color='rgb(200,130,100)', marker_line_color='rgb(8,48,107)', marker_line_width=1.5, opacity=0.6)
fig.update_layout(xaxis_tickangle=-45)
fig.show()